### ISSUE TITLE
Contacts invitation system

### ISSUE THREAD

**Issue by shaam48** [shaam48/bloccit#18]

**Comment by shaam48** [comment]
@cbeck So the idea here is that I would like a feature where users can import emails from their respective email providers whether Gmail, Outlook or any other. Thereafter, I'd like to send an invite email to all these imported email addresses. Any tips or gems?

**Comment by cbeck** [comment]
You mean their contact list, right? Not actual emails? 

A quick google search yielded this: https://github.com/cardmagic/contacts

I haven't personally used it, but it looks like there are several gems of that sort.
